// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eoqchonehztspwtjiswj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvcWNob25laHp0c3B3dGppc3dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNjcyMDQsImV4cCI6MjA2Mjc0MzIwNH0.nqf0uJGiCXMFcZNWNra5RdCOivlfwyZZxXFWNib6EZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);