// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dflajczpxifkdjfphejx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmbGFqY3pweGlma2RqZnBoZWp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5OTI5OTcsImV4cCI6MjA2MjU2ODk5N30.Q5U_SRaKMDztTm_-kaWd4aNXFpn-vVpbsYtwOsRakjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);